version: "2"
services:
  keycloak:
    build: .
    ports:
     - "8080:8080"
    volumes:
     - ./web:/code
    links:
     - mysql:mysql
    environment:
     - KEYCLOAK_USER=root
     - KEYCLOAK_PASSWORD=password
     - MYSQL_PASSWORD=root
     - MYSQL_USERNAME=root
     - MYSQL_DATABASE=keycloak
     - MYSQL_PORT_3306_TCP_ADDR=mysql
     - MYSQL_PORT_3306_TCP_PORT=3306
  mysql:
    image: mysql
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=keycloak
